version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/usr/src/app/uploads # Montar a pasta de uploads
    environment:
      - PORT=3001
    networks:
      - my_network

networks:
  my_network:
