# Use uma imagem base do Node.js
FROM node:17

# Crie um diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie os arquivos necessários para o contêiner
COPY .git ./.git
COPY .gitignore ./
COPY id_rsa /usr/src/app/.ssh/id_rsa
COPY id_rsa.pub /usr/src/app/.ssh/id_rsa.pub
COPY docker-compose.prod.yml ./
COPY docker-compose.dev.yml ./
COPY Dockerfile.prod ./
COPY Dockerfile.dev ./
COPY .env.example ./
COPY package*.json ./
COPY server.js ./
COPY .env ./
COPY public ./public
COPY uploads ./uploads

# Instale as dependências do Node.js
RUN npm install

RUN eval $(ssh-agent -s) && ssh-add /usr/src/app/.ssh/id_rsa

# Exponha a porta que sua aplicação Node.js estará ouvindo
EXPOSE 3001

# Comando para iniciar a aplicação
CMD [ "npm", "start" ]
