FROM node:17

WORKDIR /usr/src/app

COPY .git ./.git
COPY .gitignore ./
COPY id_rsa /usr/src/app/.ssh/id_rsa
COPY id_rsa.pub /usr/src/app/.ssh/id_rsa.pub
COPY docker-compose.prod.yml ./
COPY docker-compose.dev.yml ./
COPY Dockerfile.prod ./
COPY Dockerfile.dev ./
COPY .env.example ./
COPY package*.json ./
COPY server.js ./
COPY .env ./
COPY public ./public
COPY uploads ./uploads

RUN npm install

RUN eval $(ssh-agent -s) && ssh-add /usr/src/app/.ssh/id_rsa

EXPOSE 3001

CMD [ "npm", "start" ]
